### PR TITLE
moved appbar and changed patient summary to a material-ui card

### PR DESCRIPTION
**Pull request by kyjohnso**
I added a material-ui react card element to the patient component and in the process of adding the app bar, I extracted the appbar from the app.jsx component and put it in its own component

### CODE REVIEW

**Comment by kylewalters18** [comment]
Heyo! Kyles writing code!

**Comment by kylewalters18** [comment]
Setting up your text editor with eslint should help with the style errors. I use Atom and that's pretty easy to set up linting

**Comment by kyjohnso** [comment]
You know it, I will look at the eslint in vim

**Comment by clintwojtowicz** [comment]
Vim????? What is this 1989?

**Comment by kyjohnso** [comment]
it is the text editor i used in elementary school and it is the one i am
sticking with

**Comment by kyjohnso** [comment]
with the latest commits the travis ci report only has errors that have to
do with defining variables that are not used, and they are mostly in code
that I did not touch. Could one of you look at the code and either approve
merge or let me know what needs to change?

Also, I plan on implementing the notes in the database and patient.jsx
component today, should i create another branch off master or branch off my
existing branch?

**Review by clintwojtowicz — APPROVED** [review]

**Pull request merged**
